travis:
  secure:
    BINSTAR_TOKEN: d8NULB0EmIn7xFtwDACWgFp43dazwinEmXCrK/0fQ/Fq1kgszA2s9d2DmCC7HlmNa6aQeDSbzKMAT4loADMXXF2Zk254qqtih8LdqCCueBZKp3A6Bw5glR+kumDZ2HbALeJn+pTOsp/LaIZFGzmo+u0u+aoSbItGORrNGiRFH3nFU3QqVhc5mwinNLSuHTkiE7InpVxYXixUk2juqEhMxgFYVBUVO3KlYJkSY1owCd73YDhamZP9eXAXIBzVgRxDrt+SxGkQSqeMW5EEC80eshTb/6zu4Osb5g92ykQWFHEzlZBoVa0RLHnlP2OJFAzM5kFBYzAIbJhRFZqch+4zPbb2epL/U4kdwkGaBsb6nHgw3hbGIv5CH5ElEhXtkrVJIq5tAgf1uZSJvILweUnasdAEqfl71xLqoYiHu5YD0l2WhO8BxR/4DY01mwcByuaXejqjevE3p3FmKQEEAMPE4u7+Ifh2WNSuvtN9hat8Wobtp7fGKBEjQs7w013A++jJvvYiIITGrRDqOM/LDO6pLXbicDM5kKYDfM3SeCXUE2gcLAId8ZkkB7bJ+vlhDTPyL3ExuRkk3XaiJCjy/E65CmlIxk4hgnqMisQzdcCIlqbWl+90JrAxKrLJAkqgbGdwPX1Ca3ZTU2gSWzLbgAhI0I4qc3YZ+22dsngj46WzpYk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
